#!/usr/bin/env ansible-playbook

- name: Install utilities
  hosts: all
  become: true

  pre_tasks:
    - include: tasks/settings.yml
  roles:
    - {role: motd, tags: 'motd'}
    - {role: dockpack.base_common, tags: 'common'}
    - {role: dockpack.base_utils, tags: 'utils'}
    - {role: dockpack.base_goss, tags: 'goss'}

- name: Install web server
  hosts: build_master
  become: true
  roles:
    - {role: pki, tags: 'pki'}
    - {role: firewall, tags: 'firewall'}
    - {role: jdauphant.nginx, tags: 'nginx'}
    - {role: homepage, tags: 'homepage'}

- name: Install build tools
  hosts: build_master:ubuntu
  become: true
  vars:
    miniconda_install: true
    DTSVER: 8
  roles:
    - role: dockpack.base_git
      when: collections_enabled
    - {role: dockpack.base_cmake, tags: 'cmake'}
    - {role: dockpack.base_gcc, tags: 'gcc'}
    - {role: dockpack.base_boost, tags: 'boost'}
    - {role: dockpack.base_java8, tags: 'java8'}
    - {role: dockpack.base_ant, tags: 'ant'}
    - {role: dockpack.base_maven, tags: 'maven'}
    - {role: dockpack.base_gradle, tags: 'gradle'}
    - {role: dockpack.base_miniconda, tags: 'conda'}

- name: Install Jenkins
  hosts: build_master
  become: true

  roles:
    - {role: jenkins, tags: 'jenkins'}
    - {role: selenium, tags: 'selenium'}
    - {role: dockpack.base_python, tags: 'python'}
    - { role: bbaassssiiee.sonar, tags: 'sonar' }
    - { role: bbaassssiiee.artifactory, tags: 'artifactory' } # for built stuff

- name: Install docker
  hosts: centos7
  become: true

  roles:
    - {role: dockpack.base_docker, tags: 'docker'}
