---
- name: Build Server
  hosts: dev:lab
  remote_user: vagrant
  sudo: yes

  roles:
    - bbaassssiiee.commoncentos
    - httpd
    - jenkins                           # Use Jenkins to build
    - hullufred.nexus                   # Nexus is used as library repository
    - pcextreme.mariadb                 # Artifactory & sonar use mariadb
    - bbaassssiiee.artifactory          # Artifactory is our build repository
    - bbaassssiiee.sonar                # SonarQube reports on code quality

  tasks:
    - include: tasks/settings.yml


- name: Target server
  hosts: target
  remote_user: vagrant
  sudo: yes
  vars:
    homedir: "{{ lookup('env','HOME') }}"

  pre_tasks:
    - include: tasks/settings.yml

  roles:
    - bbaassssiiee.commoncentos
    - geerlingguy.java
    - issue
    - postgres
    - hudecof.tomcat

  tasks:
    - include: tasks/tomcat_settings.yml

- name: Ubuntu Client
  hosts: ubuntu
  remote_user: vagrant
  sudo: yes
  gather_facts: yes

  roles:
    - geerlingguy.java
    - ansible-maven

- name: Windows client
  hosts: windows
  remote_user: IEUser
  gather_facts: no

  roles:
  - ansible-oasis-maven

  tasks:
    - include: tasks/windows_settings.yml

