#!/usr/bin/env ansible-playbook
- name: Build Server
  hosts: dev:build
  become: yes

  roles:
    - bbaassssiiee.commoncentos
    - { role: common, tags: 'common' }
    - { role: ntp, tags: 'ntp' }
#    - firewall
    - RHEL7-CIS
    - { role: bbaassssiiee.el_postgres_role, tags: 'postgres' }
    - { role: httpd, tags: 'httpd' }
#    - { role: php, tags: 'php' } needs nginx
    - { role: cplusplus, tags: 'cplusplus' }
    - { role: git, tags: 'git' }
    - { role: nodejs, tags: 'nodejs' }
    - { role: npm, tags: 'npm' }
    - { role: perl, tags: 'perl' }
    - { role: python, tags: 'python' }
    - { role: golang, tags: 'golang' }

    - { role: oracle_java8, tags: 'oracle_java8' }
    - { role: bbaassssiiee.artifactory, tags: 'artifactory' }
    - { role: jenkins, tags: 'jenkins' }
    - { role: ansible-nexus, tags: 'ansible-nexus' }
    - { role: bbaassssiiee.sonar, tags: 'sonar' }
    - { role: ant, tags: 'ant' }
    - { role: maven, tags: 'maven' }
    - { role: gradle, tags: 'gradle' }

  tasks:
    - include: tasks/settings.yml

- name: Target server
  hosts: target
  remote_user: vagrant
  become: yes
  vars:
    homedir: "{{ lookup('env','HOME') }}"

  pre_tasks:
    - include: tasks/settings.yml

  roles:
    - bbaassssiiee.commoncentos 
    - common
    - ntp
    - oracle_java8
#    - hudecof.tomcat
    - ansible-jenkins-slave
#    - ansible-selenium-role

  tasks:
    - include: tasks/tomcat_settings.yml
    - include: tasks/install_docker.yml

- name: Ubuntu Box
  hosts: ubuntu
  remote_user: vagrant
  become: yes
  gather_facts: yes

  roles:
    - oracle_java8
    - ansible-selenium-role
    - ansible-jenkins-slave

- name: Windows client
  hosts: windows
  remote_user: IEUser
  gather_facts: no

  roles:
  - ansible-oasis
  - ferhaty.jenkins-slave
  - windows-selenium-role

  tasks:
    - include: tasks/windows_settings.yml

