#!/usr/bin/env ansible-playbook
- name: Build Server
  hosts: build
  gather_facts: no
  remote_user: vagrant
  become: yes

  tasks:

  - name: 'verify tcp listening socket for Apache'
    wait_for: port=443 timeout=20 delay=1

  - name: 'verify tcp listening socket for Postgres'
    wait_for: port=5432 timeout=30

  - name: 'verify tcp listening socket for Jenkins'
    wait_for: port=8080 timeout=30

  - name: 'verify tcp listening socket for Artifactory'
    wait_for: port=8081 timeout=30

  - name: 'verify tcp listening socket for Sonar'
    wait_for: port=9000 timeout=10
    ignore_errors: yes

  - name: 'verify local import of pki/buildserverCA.cer'
    become: no
    changed_when: no
    local_action: get_url url=https://build/ validate_certs=yes timeout=10 dest=/build/null

  - name: 'verify https connectivity to Jenkins'
    become: no
    local_action: uri url=https://build/jenkins/jobConfigHistory/ validate_certs=no status_code=200

  - name: 'verify https connectivity to Artifactory'
    become: no
    local_action: uri url=https://build/artifactory/webapp/#/artifacts/browse/tree/General/ext-release-local 
                  status_code=200 validate_certs=no

  - name: 'verify https connectivity to Jenkins'
    become: no
    local_action: uri url=https://build/jenkins/ method=GET validate_certs=no status_code=200
