setup-x86_64.exe ^
--quiet-mode ^
--site ^
http://cygwin.mirrorcatalogs.com ^
--packages ^
alternatives              ,^
base-cygwin               ,^
base-files                ,^
bash                      ,^
bash-completion           ,^
binutils                  ,^
bzip2                     ,^
ca-certificates           ,^
coreutils                 ,^
csih                      ,^
curl                      ,^
cygrunsrv                 ,^
cygutils                  ,^
cygwin                    ,^
cygwin-devel              ,^
dash                      ,^
diffutils                 ,^
editrights                ,^
file                      ,^
findutils                 ,^
gawk                      ,^
gcc-core                  ,^
gcc-g++                   ,^
getent                    ,^
git                       ,^
git-completion            ,^
git-email                 ,^
grep                      ,^
groff                     ,^
gzip                      ,^
hostname                  ,^
info                      ,^
ipc-utils                 ,^
less                      ,^
libargp                   ,^
libatomic1                ,^
libattr1                  ,^
libblkid1                 ,^
libbz2_1                  ,^
libcloog-isl4             ,^
libcom_err2               ,^
libcrypt0                 ,^
libcurl4                  ,^
libdb5.3                  ,^
libedit0                  ,^
libexpat1                 ,^
libffi6                   ,^
libgcc1                   ,^
libgdbm4                  ,^
libgmp10                  ,^
libgnutls28               ,^
libgomp1                  ,^
libgssapi_krb5_2          ,^
libguile17                ,^
libhogweed2               ,^
libiconv                  ,^
libiconv2                 ,^
libidn11                  ,^
libintl8                  ,^
libisl10                  ,^
libk5crypto3              ,^
libkrb5_3                 ,^
libkrb5support0           ,^
libltdl7                  ,^
liblzma5                  ,^
libmetalink3              ,^
libmpc3                   ,^
libmpfr4                  ,^
libncursesw10             ,^
libnettle4                ,^
libopenldap2_4_2          ,^
libopenssl100             ,^
libp11-kit0               ,^
libpcre1                  ,^
libpipeline1              ,^
libpopt0                  ,^
libquadmath0              ,^
libreadline7              ,^
libsasl2_3                ,^
libsmartcols1             ,^
libsqlite3_0              ,^
libssh2_1                 ,^
libssp0                   ,^
libstdc++6                ,^
libtasn1_6                ,^
libuuid-devel             ,^
libuuid1                  ,^
libwrap0                  ,^
libyaml-devel             ,^
libyaml0_2                ,^
login                     ,^
lynx                      ,^
make                      ,^
man-db                    ,^
mintty                    ,^
openssh                   ,^
openssl                   ,^
p11-kit                   ,^
p11-kit-trust             ,^
perl                      ,^
perl-Authen-SASL          ,^
perl-Digest-HMAC          ,^
perl-Error                ,^
perl-IO-Socket-SSL        ,^
perl-MailTools            ,^
perl-Net-SMTP-SSL         ,^
perl-Net-SSLeay           ,^
perl-TimeDate             ,^
perl_autorebase           ,^
perl_base                 ,^
popt                      ,^
python                    ,^
python-crypto             ,^
python-paramiko           ,^
python-setuptools         ,^
python-six                ,^
rebase                    ,^
rsync                     ,^
run                       ,^
sed                       ,^
tar                       ,^
terminfo                  ,^
tzcode                    ,^
util-linux                ,^
vim-minimal               ,^
w32api-headers            ,^
w32api-runtime            ,^
wget                      ,^
which                     ,^
windows-default-manifest  ,^
xz                        ,^
zlib0                     ,^
zsh                       ,^
                          ,^
