#!/bin/bash -e
myUser=$1
myHome=$(su - $myUser -c 'echo $HOME')

# create enough space for database and backup

mv $myHome/sonar.properties $SONAR_HOME/conf
mkdir -p /home/sonar_backup
chown -R $myUser /home/sonar_backup
chown -R $myUser $SONAR_HOME
chmod 700 /home/$myUser/.ssh
chmod 600 /home/$myUser/.ssh/backup
service mysqld start
mysql -u root < /home/$myUser/bin/create_database.sql || true

cp ${myHome}/index.html /var/www/html
service httpd restart
