---

- name: 'Install demo jobs'
  file: state=directory dest={{jenkins_data}}/jobs/{{ item }}/builds owner=jenkins group=jenkins
  with_items:
    - game-of-life
    - oasis
  tags:
    - config

- name: 'create demo jobs config.xml'
  template: src={{ item }}/config.xml dest={{jenkins_data}}/jobs/{{ item }}/config.xml owner=jenkins group=jenkins mode=0600
  with_items:
    - game-of-life
    - oasis
  tags:
    - config

- name: 'create legacyIds for demo job'
  file: state=touch dest={{jenkins_data}}/jobs/{{ item }}/builds/legacyIds owner=jenkins group=jenkins
  with_items:
    - game-of-life
    - oasis

- name: 'create symlinks for game-of-life job'
  file: state=link force=yes src=-1 dest={{jenkins_data}}/jobs/game-of-life/builds/{{item}} owner=jenkins group=jenkins
  with_items:
    - lastFailedBuild
    - lastStableBuild
    - lastSuccessfulBuild
    - lastUnstableBuild
    - lastUnsuccessfulBuild

- name: 'create symlinks for oasis job'
  file: state=link force=yes src=-1 dest={{jenkins_data}}/jobs/oasis/builds/{{item}} owner=jenkins group=jenkins
  with_items:
    - lastFailedBuild
    - lastStableBuild
    - lastSuccessfulBuild
    - lastUnstableBuild
    - lastUnsuccessfulBuild
